name: workoutbuddy
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dio: ^4.0.4
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13
  swipable_stack: ^1.2.0
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - images/
    - assets/images/
