// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFzyYeS6plVqOMvajZu-iB2fxd0Avwl1U',
    appId: '1:305077722290:web:4c4975e3cef74ac927fdab',
    messagingSenderId: '305077722290',
    projectId: 'workoutbuddy-app',
    authDomain: 'workoutbuddy-app.firebaseapp.com',
    storageBucket: 'workoutbuddy-app.appspot.com',
    measurementId: 'G-JTHB61DLEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCv06ye-oivJAFdc4jTRBuauxA85-qL4',
    appId: '1:305077722290:android:9f6fa83b6c00335727fdab',
    messagingSenderId: '305077722290',
    projectId: 'workoutbuddy-app',
    storageBucket: 'workoutbuddy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAULh2pxrvxH_K1P-jgcn0NMiU2Ptrh33I',
    appId: '1:305077722290:ios:3bda754f1b05209d27fdab',
    messagingSenderId: '305077722290',
    projectId: 'workoutbuddy-app',
    storageBucket: 'workoutbuddy-app.appspot.com',
    iosClientId: '305077722290-srfrbnnbqq88aanrv4cb70ee7g6qoi7f.apps.googleusercontent.com',
    iosBundleId: 'com.memoriasit.app',
  );
}
